language: node_js
node_js:
- '0.12'
before_script:
- npm install -g npm grunt-cli mocha istanbul bower
- gem update --system
- gem install compass
- npm install --quiet
- bower install
services:
- mongodb
- redis-server
script:
- grunt --gruntfile ./Gruntfile.js
notifications:
  slack: amida:GclZqFLfLqmjWZ4bwUbRIw5M