language: node_js
node_js:
- '0.12'
install:
- npm install -g npm
- npm install -g bower grunt-cli 
- npm install -g mocha 
- npm install -g istanbul
- npm install --quiet
- bower install
- ./node_modules/protractor/bin/webdriver-manager update
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start 
- nohup bash -c "./node_modules/protractor/bin/webdriver-manager start 2>&1 &" - sleep 5
services:
- mongodb
- redis-server
script:
- grunt --gruntfile ./Gruntfile.js
- grunt travis-protractor --gruntfile ./Gruntfile.js
notifications:
  slack: amida:GclZqFLfLqmjWZ4bwUbRIw5M