language: node_js
node_js:
- '0.12'
before_script:
- npm install -g npm
- npm install -g grunt-cli 
- npm install -g mocha 
- npm install -g istanbul
- npm install --quiet
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start 
- nohup bash -c "./nodemodules/protractor/bin/webdriver-manager start 2>&1 &" - sleep 5
services:
- mongodb
- redis-server
script:
- grunt --gruntfile ./Gruntfile.js
- grunt test --gruntfile ./Gruntfile.js
notifications:
  slack: amida:GclZqFLfLqmjWZ4bwUbRIw5M